apiVersion: v1
kind: Service
metadata:
  name: slskd
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - nodePort: 32266
    port: 82
    protocol: TCP
    targetPort: 5030
  selector:
    app: slskd
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: localhost
